#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
layout(r8, binding = 0) uniform writeonly image3D detailNoise_output;

float fbmWorley3D(vec3 p); 

void main() {
    ivec3 pixel_coords = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 dims = imageSize(detailNoise_output);

    if (pixel_coords.x >= dims.x || pixel_coords.y >= dims.y || pixel_coords.z >= dims.z) return;

    vec3 p = vec3(pixel_coords) / float(dims.x);
    float detailVal = 1.0 - fbmWorley3D(p * 16.0); 

    imageStore(detailNoise_output, pixel_coords, vec4(detailVal, 0.0, 0.0, 0.0));
}
