#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
layout(r8, binding = 0) uniform writeonly image3D noise3D_output;

void main() {
				ivec3 pixel_coords = ivec3(gl_GlobalInvocationID.xyz);
				ivec3 dims = imageSize(noise3D_output);

				if (pixel_coords.x >= dims.x || pixel_coords.y >= dims.y || pixel_coords.z >= dims.z) return;

				vec3 p = vec3(pixel_coords) / float(dims.x);
				float noiseVal = fbm3D(p * 8.0); 

				imageStore(noise3D_output, pixel_coords, vec4(noiseVal, 0.0, 0.0, 0.0));
}
