#version 430 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(r32f, binding = 1) uniform writeonly image2D heightmap;

uniform vec2 u_offset; 
uniform float u_scale; 

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(heightmap);
    
    if (pixel_coords.x >= dims.x || pixel_coords.y >= dims.y) return;

    vec2 uv = vec2(pixel_coords) / vec2(dims);
    vec2 noisePos = (uv * u_scale) + u_offset;
    float height = fbmWorley(noisePos, u_scale);

    imageStore(heightmap, pixel_coords, vec4(height, 0.0, 0.0, 0.0));
}
